name: Newman Run

on:
  pull_request:
    branches:
    - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: newman  run https://api.getpostman.com/collections/6450325-c2343b08-0b8c-48cd-865e-9300e339f1f7?apikey=PMAK-636ea7ec596d03060715762f-e218eb33eac4fa5a9a80eb64871f082145
